# Generated by Django 4.2 on 2023-04-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('consignee', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
            ],
        ),
    ]
