# Generated by Django 4.2 on 2023-04-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='amount',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='consignee',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='destination',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='sno',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='weight',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
