# Generated by Django 4.2 on 2023-04-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_mymodel_amount_alter_mymodel_consignee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='amount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='consignee',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='destination',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='sno',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='weight',
            field=models.CharField(max_length=50),
        ),
    ]
