# Generated by Django 4.2 on 2023-04-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_billno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Billno',
        ),
    ]
