# Generated by Django 4.2 on 2023-04-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_billno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billno',
            name='billno',
            field=models.IntegerField(),
        ),
    ]
