# Generated by Django 4.2 on 2023-04-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_billno_billno'),
    ]

    operations = [
        migrations.AddField(
            model_name='billno',
            name='billtotal',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
